-- AlterTable
ALTER TABLE `applications` ADD COLUMN `desiredDate` DATE NULL,
    ADD COLUMN `desiredInspectType` ENUM('DOCUMENT', 'SAMPLING') NULL,
    ADD COLUMN `extra` JSON NULL,
    ADD COLUMN `installer2` VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN `occupancy` VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN `witness` VARCHAR(60) NOT NULL DEFAULT '',
    ADD COLUMN `witnessPhone` VARCHAR(40) NOT NULL DEFAULT '',
    ADD COLUMN `worker1` VARCHAR(60) NOT NULL DEFAULT '',
    ADD COLUMN `worker2` VARCHAR(60) NOT NULL DEFAULT '';
